[package]
edition = "2024"
name = "fbd"
version = "0.1.0"

[dependencies]
noto-sans-mono-bitmap = {version = "0.3.1", features = ["regular", "size_20", "unicode-basic-latin", "unicode-specials"], default-features = false}
rstd = {path = "../../rstd"}
spin = "0.9.8"
