cargo-features = ["per-package-target"]

[package]
name = "acpid"
version = "0.1.0"
edition = "2024"

[dependencies]
aml = { git = "https://github.com/rw-vanc/acpi.git", branch = "cumulative" }
plain = "0.2.3"
rstd = { path = "../../rstd" }
spin = "0.9.8"
